ss_platform:
    resource: "@SSPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /
    defaults:
        _controller: SSUserBundle:User:signin
signup:
    path: /signup
    defaults:
        _controller: SSUserBundle:User:signup
login_check:
    path: /login_check

logout:
    path: /logout
