ss_platform:
    resource: "@SSPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: platform/login
    defaults:
        _controller: SSUserBundle:Security:login

login_check:
    path: platform/login_check

logout:
    path: platform/logout
