ss_platform:
    resource: "@SSPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /login
    defaults:
        _controller: SSUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
