<?php

namespace SS\PlatformBundle\Repository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOffresBy($annee,$profil,$domaine,$intitule)
    {
        $query=$this->createQueryBuilder('o');

        $query
            ->where('o.profil LIKE :profil')
            ->setParameter('profil',$profil.'%')
            ->andWhere('o.dateOffre LIKE :annee')
            ->setParameter('annee',$annee.'%')
            ->andWhere('o.domaine LIKE :domaine')
            ->setParameter('domaine','%'.$domaine.'%')
            ->andWhere('o.intitule LIKE :intitule')
            ->setParameter('intitule','%'.$intitule.'%')
           ;

        return $query->getQuery()->getResult();
    }

}
