# src/SS/PlatformBundle/Resources/config/routing.yml

ss_platform_home:
    path:    /{page}
    defaults:
        _controller: SSPlatformBundle:Advert:index
        page:    1
    requirements:
        page: \d*
    
ss_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:view
    requirements:
        id: \d+

ss_platform_addOffre:
    path:      /addO
    defaults:
        _controller: SSPlatformBundle:Advert:addO

ss_platform_addEntreprise:
    path:      /addE
    defaults:
        _controller: SSPlatformBundle:Advert:addE

ss_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:editO
    requirements:
        id: \d+

ss_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:deleteO

ss_platform_editC:
    path:      /edit{id}
    defaults:
        _controller: SSPlatformBundle:Advert:editC
    requirements:
        id: \d+

ss_platform_deleteC:
    path:      /delete{id}
    defaults:
        _controller: SSPlatformBundle:Advert:deleteC

        
ss_platform_offres:
    path: /offres
    defaults:
        _controller: SSPlatformBundle:Advert:offres

ss_platform_entreprises:
    path: /entreprises
    defaults:
        _controller: SSPlatformBundle:Advert:Entreprises

ss_platform_offresE:
    path: /offres/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:offresE


ss_platform_searchOffres:
    path: /search
    defaults:
        _controller: SSPlatformBundle:Advert:searchOffres