# src/SS/PlatformBundle/Resources/config/routing.yml

ss_platform_home:
    path:    /{page}
    defaults:
        _controller: SSPlatformBundle:Advert:index
        page:    1
    requirements:
        page: \d*
    
ss_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:view
    requirements:
        id: \d+

ss_platform_addOffre:
    path:      /addO
    defaults:
        _controller: SSPlatformBundle:Advert:addO

ss_platform_addEntreprise:
    path:      /addE
    defaults:
        _controller: SSPlatformBundle:Advert:addE

ss_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:editO
    requirements:
        id: \d+

ss_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: SSPlatformBundle:Advert:deleteO
